### PR TITLE
Instructional Design Documentation

### PR DESCRIPTION
**Pull request by jswope00**
Adding discussed documentation for instructional Design: 
1. Instructional Design Overview
2. Course Development Process
3. Instructional Design Templates

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @jswope00!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by openedx-webhooks** [comment]
@jswope00 Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/docs.openedx.org&entry.867055334=https://github.com/openedx/docs.openedx.org/pull/232&entry.1484655318=https://github.com/jswope00&entry.752974735=2022-12-20+18:04&entry.1917517419=2022-12-20+20:52&entry.2133058324=No) so we can improve your experience in the future.

**Comment by feanil** [comment]
@jswope00 it looks like this got automatically closed by github when I merged my branch into `main`.  I think you should be able to just re-open the PR against `main`.

**Comment by jswope00** [comment]
Resubmitted as Pull Request #233 to the main branch instead of the closed feanil/id_pages branch.

**Pull request closed without merging**
