### PR TITLE
docs: Add complete course authoring MFE flags to Redwood release notes

### PR DESCRIPTION
**Pull request by sarina**
image

https://docsopenedxorg--521.org.readthedocs.build/en/521/community/release_notes/redwood/dev_op_release_notes.html#flags-specific-to-the-new-course-authoring-mfe

### CODE REVIEW

**Comment by sarina** [comment]
@arbrandes can you confirm these are all the course authoring flags?

**Comment by arbrandes** [comment]
@sarina, all the new ones that we're enabling by default in Tutor, yes!

**Review by arbrandes — APPROVED** [review]
+1

**Review by feoh — APPROVED** [review]

**Comment by feoh** [comment]
Thanks for catching this @sarina!

**Pull request merged**
