### PR TITLE
docs: Add a quickstart for people's first docs PR.

### PR DESCRIPTION
**Pull request by feanil**
We walk the reader through the process of making a small update to the
documentation repo using the github UI.

PR Build is here: https://docsopenedxorg--55.org.readthedocs.build/en/55/

### CODE REVIEW

**Comment by feanil** [comment]
Current dependencies on/for this PR:
* main
  * **PR #55** <a href="https://app.graphite.dev/github/pr/openedx/docs.openedx.org/55" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/openedx/docs.openedx.org/55?utm_source=stack-comment).

**Comment by markH-Docemus** [comment]
@feanil looks good

**Comment by jmakowski1123** [comment]
@feanil just confirming this is the page with the new changes to review, correct? https://docsopenedxorg--55.org.readthedocs.build/en/55/documentors/quickstarts/first_documentation_pr.html

**Comment by feanil** [comment]
@jmakowski1123 yep, that's the page.

**Review by Carlos-Muniz — APPROVED** [review]

**Pull request merged**
