### PR TITLE
docs: add seealso for oep58 in enable-translations-new-repo.rst

### PR DESCRIPTION
**Pull request by OmarIthawi**
The `seealso` link will work after this branch is merged with `main`:

<kbd>image</kbd>

This contribution is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @OmarIthawi!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by brian-smith-tcril** [comment]
This diff looks huge, I think we should rebase `oep-58-howto` on latest `main` (or just merge `main` into `oep-58-howto` with the intention of getting `oep-58-howto` into main via squash+merge)  and then see how it looks.

**Comment by OmarIthawi** [comment]
> This diff looks huge, I think we should rebase `oep-58-howto` on latest `main` (or just merge `main` into `oep-58-howto` with the intention of getting `oep-58-howto` into main via squash+merge) and then see how it looks.

Correct @brian-smith-tcril. It looks huge.

The GitHub makes the diff look confusing but it's pretty legit and shouldn't show up in https://github.com/openedx/docs.openedx.org/pull/363.

However, I'm all in for updating `oep-58-howto` branch whether it's a rebase or a merge. Please update it so I can rebase this branch so it shows up cleanly in GitHub UI.

**Comment by brian-smith-tcril** [comment]
@OmarIthawi this was closed because I merged the `oep-58-howto` branch into `main`. Making a new PR to `main` is the ideal path forward here.

**Pull request closed without merging**
