### PR TITLE
Add Copy Paste Educator How To guide

### PR DESCRIPTION
**Pull request by sarina**
Content authored by Jenna in https://docs.google.com/document/d/1IjkJG_zL7lYsFK7945V6jSGev3hHL5ESI9Uw27SwI3w/edit

### CODE REVIEW

**Comment by sarina** [comment]
@feanil can you review? rendered page: https://docsopenedxorg--348.org.readthedocs.build/en/348/educators/how-tos/copy_paste_course_content.html

**Review by feanil — APPROVED** [review]
Looks good, my one suggestion that you can take or leave would be to highlight the exact part of the picture you want people to notice, I usually do a red box or an arrow to point to the exact element they should be paying attention to.

**Comment by sarina** [comment]
Good idea - can you take a look at the ones I've added?

**Comment by feanil** [comment]
They look great!  Thanks for updating!

**Pull request merged**
