### PR TITLE
docs: Update 'install tutor nightly' command.

### PR DESCRIPTION
**Pull request by apexDev37**
Under the section, `Install Tutor Nightly` update the command `tutor dev quickstart` to `tutor dev launch` to configure and provision an Open edX instance. `quickstart` is not listed as one of the options commands for `tutor dev`.

### Update to the tutorial: **Quick Start: First Open edX Pull Request**

**Navigation:**
```
|--- Quickstarts
     |--- Developers: Contribute to Open edX
           |--- Quick Start: First Open edX Pull Request
                 |--- #Section: Installing Tutor Nightly

```
Here is the documentation [link](https://docs.openedx.org/en/latest/developers/quickstarts/first_openedx_pr.html#installing-tutor-nightly). 

**Problem:**
When following the tutorial I encountered a blocker in executing one of the provided commands: `tutor dev quickstart`.
**Expected:**
An interactive session to configure and provision an Open edX instance. 
**Actual:**
The following terminal output error message:
```
Usage: tutor dev [OPTIONS] COMMAND [ARGS]...
Try 'tutor dev -h' for help.

Error: No such command 'quickstart'.
```
**Additional:**
`quickstart` does not appear as one of the commands for `tutor dev`.
List usage commands with the following command, `tutor dev -h`.
Output from executing the command:
```
Usage: tutor dev [OPTIONS] COMMAND [ARGS]...

  Run Open edX locally with development settings

Options:
  -h, --help  Show this message and exit.

Commands:
  copyfrom  Copy files/folders from a container directory to the local...
  dc        Direct interface to docker-compose.
  do        Run a custom job in the right container(s).
  exec      Run a command in a running container
  launch    Configure and run Open edX from scratch
  logs      View output from containers
  reboot    Reboot an existing platform
  restart   Restart some components from a running platform.
  run       Run a command in a new container
  start     Run all or a selection of services.
  status    Print status information for containers
  stop      Stop a running platform
  upgrade   Perform release-specific upgrade tasks.
```

**Context:**
The host machine runs Ubuntu Focal. Python version: `3.8.10`. The only configuration run by the user was the instructions specified in the tutorial, **Quick Start: First Open edX Pull Request**. Prior to this, nothing concerning Open edX or Tutor was installed or set up on the user's host machine.
 
**Fix:**
Suggest an edit to update the provided command from `tutor dev quickstart` to `tutor dev launch` to configure and provision an Open edX instance.

### CODE REVIEW

**Comment by mphilbrick211** [comment]
Hi @apexDev37! Thank you for this contribution! Please let me know if you have any questions regarding submitting your [CLA form.](https://openedx.atlassian.net/wiki/spaces/COMM/pages/941457737/How+to+start+contributing+to+the+Open+edX+code+base)

**Comment by apexDev37** [comment]
@mphilbrick211, I managed to complete the developer Quick Start: [**First Open edX Pull Request**](https://docs.openedx.org/en/latest/developers/quickstarts/first_openedx_pr.html#). I encountered a couple of errors due to the documentation being outdated. I would like to share the updates I made to complete the Quick Start successfully (sourced for the Tutor [documentation](https://docs.tutor.overhang.io/dev.html) and [`CHANGELOG`](https://github.com/overhangio/tutor/blob/master/CHANGELOG.md)).

Kindly advise me. Should I open a new pull request or add to this existing one?
Note, some modifications require major section updates.

**Comment by mphilbrick211** [comment]
@feanil - flagging this in case you have some input!

**Comment by feanil** [comment]
@mphilbrick211 this looks good to merge once the CLA process has been fully executed.

**Comment by apexDev37** [comment]
The CLA process is complete and all checks have passed✅

**Comment by mphilbrick211** [comment]
> The CLA process is complete and all checks have passed✅

Perfect, @apexDev37! I've marked this as ready for review.

**Review by feanil — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@apexDev37 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/docs.openedx.org&entry.867055334=https://github.com/openedx/docs.openedx.org/pull/368&entry.1484655318=https://github.com/apexDev37&entry.752974735=2023-08-10+18:21&entry.1917517419=2023-08-22+17:06&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by apexDev37** [comment]
First, @mphilbrick211 and @feanil, thank you for the great support🌍
I raised a concern about an outdated section I encountered in the same developer Quick Start: [First Open edX Pull Request](https://docs.openedx.org/en/latest/developers/quickstarts/first_openedx_pr.html#).

**Comment by apexDev37** [comment]
**Section:** [Mounting edx-platform](https://docs.openedx.org/en/latest/developers/quickstarts/first_openedx_pr.html#id7)
**Noted areas of concern include:**
1. The provided command `tutor dev run --mount=./edx-platform lms bash` to mount to a local edX checkout is [deprected](https://github.com/overhangio/tutor/blob/master/CHANGELOG.md#:~:text=%F0%9F%92%A5%5BDeprecation%5D%20Remove%20the%20various%20%2D%2Dmount%20options.%20These%20options%20are%20replaced%20by%20persistent%20mounts%2C%20which%20are%20managed%20by%20the%20tutor%20mounts%20commands.%20(by%20%40regisb)).
2. Bashing into the LMS container to set up is now redundant and [performed by Tutor](https://github.com/overhangio/tutor/blob/master/CHANGELOG.md#:~:text=%5BImprovement%5D%20Running%20tutor,platform%20(by%20%40kdmccormick).) automatically on `launch`.
3. The steps provided can be significantly reduced to the following flow: `fork`, `mount`, and `launch` as specified [here](https://github.com/overhangio/tutor/blob/master/CHANGELOG.md#:~:text=%5BFeature%5D%20Automatically%20mount%20host%20folders%20at%20build%20time.%20This%20is%20a%20really%20important%20feature%2C%20as%20it%20allows%20us%20to%20transparently%20build%20images%20using%20local%20forks%20of%20remote%20repositories.%20(by%20%40regisb)).

**Source of information:**
1. Official Tutor [CHANGELOG](https://github.com/overhangio/tutor/blob/master/CHANGELOG.md)
2. Official Tutor [Documentation](https://docs.tutor.overhang.io/dev.html)

**Additional information:**
This section required updates beyond minor "suggested edits". The updates can be observed in this feature [`branch`](https://github.com/apexDev37/docs.openedx.org/tree/docs-update-quickstart-first-openedx-pull).
If applicable, I can create a new pull request.

Your advice on merging the necessary update to the developer Quickstart is appreciated.

**Pull request merged**
