### PR TITLE
Migrate Legacy Educator docs to an Orphan page

### PR DESCRIPTION
**Pull request by jswope00**
This is a migration of the legacy educator docs from https://edx.readthedocs.io/projects/open-edx-building-and-running-a-course/en/latest/index.html

@feanil @jmakowski1123 the idea is to get this up so that we can start having people review and make suggestions and pull requests directly in the github editor, based on existing docs.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @jswope00! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by feanil — COMMENTED** [review]
@jswope00 the change makes sense to me but I noticed that it's not directly navigable from the existing tree right now, is that intended?  Or should there be a  link from the educators home page to the WIP content?

**Comment by jswope00** [comment]
@feanil It is intended. This is still very much WIP and I plan to distribute this to a small group of volunteers to do all the necessary work cleaning this up before it is directly linked to the public.

**Review by feanil — APPROVED** [review]
Makes sense, merge away!

**Comment by openedx-webhooks** [comment]
@jswope00 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/docs.openedx.org&entry.867055334=https://github.com/openedx/docs.openedx.org/pull/463&entry.1484655318=https://github.com/jswope00&entry.752974735=2024-02-08+23:22&entry.1917517419=2024-02-28+18:30&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
