### PR TITLE
DRAFT: docs: Initial Migration Attempt from Legacy OLX docs. Still Erroring

### PR DESCRIPTION
**Pull request by jswope00**
A draft pull request to determine what errors are thrown in the build process on Github. It is not ready for a merge yet.

### CODE REVIEW

**Comment by sarina** [comment]
ha, I spent too long not looking at this and now the build is passed... ?!?!? .... do you want a review?

**Comment by jswope00** [comment]
@sarina Yes, I've been able to fix all the build errors. Just a general check of whether this migration of OLX from legacy to the new Open edX docs and placed in the sidebar works for you. 
And if so, do you prefer to merge, or should I merge my own passing PRs?

**Comment by sarina** [comment]
Merge when you're satisfied with your work & have addressed the conflict

**Comment by jswope00** [comment]
The main purpose for this pull request (to get support debugging errors) is done, and the work is all supplanted by this PR: https://github.com/openedx/docs.openedx.org/pull/561

Closing this pull request without merging.

**Pull request closed without merging**
