### PR TITLE
chore: cleanup

### PR DESCRIPTION
**Pull request by CodeWithEmad**
I was just reading the docs and noticed a typo. went to fix that, and found another one and another one. After a couple of hours, I found myself cleaning up most of the documentation 🤣 
I know reviewing might be painful, but look at the bright side, we will have much much cleaner documentation in the future.

This will introduce:

- followed the heading symbols for most of the docs (I might missed some. There was a lot!)
- fixing the deprecation/removal of titles for quince

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @CodeWithEmad! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by CodeWithEmad** [comment]
Also, the `graphviz` config on `maintainers_home.html` -> High Level Contribution Process has issues had some issues and didn't render anything for me (maybe something is missing on my local?)

**Comment by pdpinch** [comment]
I'm willing to review this, but the build failed.

**Comment by CodeWithEmad** [comment]
Thanks @pdpinch 
My bad. I fixed the issue and built it on my local.

**Comment by sarina** [comment]
Yikes! I'm gonna let @pdpinch review this, but I'll jump in if needed.

@CodeWithEmad - for future cleanups, it'd be preferable if you could split into smaller pull requests and/or commits. It may take a long time to review this, and require some painful rebasing.

**Comment by CodeWithEmad** [comment]
For sure @sarina.
I got a little too excited with my typo hunting.  I'll make sure to tone it down next time!

**Comment by sarina** [comment]
Definitely don't turn it down, I love the changes! I really appreciate you making them.

Ways you can consider splitting it up would be do only a group of files at a time (ie only the release notes files, then only the course ops ones, etc), or splitting out different types of changes (ie one PR that only does trailing whitespace, another PR that is just fixing header definitions, etc).

**Comment by pdpinch** [comment]
Indeed, I haven't gotten very far with this yet. If you have some time to break it into smaller, section-based PRs, that would be motivating and help us get it merged faster.

**Comment by CodeWithEmad** [comment]
Sure, I'll try to break it into smaller commits.

**Comment by CodeWithEmad** [comment]
I'll move other changes to different PRs.

**Comment by pdpinch** [comment]
@CodeWithEmad does this PR need to be reviewed, or was it replaced by #481 and #482 ?

**Comment by CodeWithEmad** [comment]
I resolved the conflicts. Could someone please look this over? 
@feanil 
@pdpinch

**Review by feanil — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@CodeWithEmad 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/docs.openedx.org&entry.867055334=https://github.com/openedx/docs.openedx.org/pull/474&entry.1484655318=https://github.com/CodeWithEmad&entry.752974735=2024-03-03+20:47&entry.1917517419=2024-06-05+17:39&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
