### PR TITLE
Re-organize documentors docs.

### PR DESCRIPTION
**Pull request by feanil**
Re-organize the documentors section to be more in-line
with how we treat and layout the other persona homes.

### CODE REVIEW

**Comment by feanil** [comment]
Current dependencies on/for this PR:
* main
  * **PR #24** <a href="https://app.graphite.dev/github/pr/openedx/docs.openedx.org/24" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/openedx/docs.openedx.org/24?utm_source=stack-comment).

**Review by Carlos-Muniz — APPROVED** [review]
The file changes are accurate to what you claimed in your commits. I would sum up the commit messages as the merge message when you squash & merge.

**Review by ormsbee — APPROVED** [review]
It looks right to me, though I do kind of which I could see it rendered out when reviewing these things.

(I guess I should just download the branch and build locally if I want that.)

**Review by markH-Docemus — APPROVED** [review]
@feanil   i did some of the same things last night.  after merging this I'll pull into my branch and reconcile

**Pull request merged**
