### PR TITLE
Update start-translating-openedx.rst

### PR DESCRIPTION
**Pull request by jesgreco**
Adding the images to the document, and adding some text to better explain the steps to translate different strings.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @jesgreco! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by feanil — COMMENTED** [review]
I think this PR and https://github.com/openedx/docs.openedx.org/pull/420 should be combined, since you're referencing images you add there.

**Comment by jesgreco** [comment]
Please, @feanil cancel this PR as I've already included the link for the images within the document in PR# 420

**Comment by openedx-webhooks** [comment]
@jesgreco Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/docs.openedx.org&entry.867055334=https://github.com/openedx/docs.openedx.org/pull/421&entry.1484655318=https://github.com/jesgreco&entry.752974735=2023-11-01+13:52&entry.1917517419=2023-11-02+18:35&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
