### PR TITLE
Fix for quickstart missing as command

### PR DESCRIPTION
**Pull request by datamatrixnull**
I was setting it up when I found that `quickstart` doesn't exist

```
(ibl) sam@sam:~/Documents/code/ibl$ tutor local quickstart
Usage: tutor local [OPTIONS] COMMAND [ARGS]...
Try 'tutor local -h' for help.

Error: No such command 'quickstart'.
```

this commands did however work for me and I got the site to run, the first to download

`tutor local start`

and then this to setup edx

`tutor local launch`

i also checked to see if `dev` was the only one with `quickstart` it doesn't have it

```
(ibl) sam@sam:~/Documents/code/ibl$ tutor dev quickstart
Usage: tutor dev [OPTIONS] COMMAND [ARGS]...
Try 'tutor dev -h' for help.

Error: No such command 'quickstart'.
```

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @datamatrixnull!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by editing the PR title.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

**Comment by mphilbrick211** [comment]
Hello, @datamatrixnull! Thank you for this contribution! Per the message above, please submit a CLA form so we can get this PR reviewed for you. Let me know if you have any questions. Thanks!

**Comment by datamatrixnull** [comment]
there seems to be two ways to do this, the first

https://github.com/cla-assistant/cla-assistant

seems to work as if I'm the owner of the project and the second

https://openedx.org/blog/the-new-home-of-the-open-edx-codebase/

is download this pdf, edit it and then send it here or to ***@***.***

if i'm on the mark on either tell me which or share instructions.

**Comment by datamatrixnull** [comment]
If it helps I'm not that interested in owning any code I push to open
source projects after all employers like this.

**Comment by mphilbrick211** [comment]
Thanks, @datamatrixnull! Once your CLA is processed the check should turn green when you re-run the tests.

**Comment by datamatrixnull** [comment]
cool this repo running make help doesn't return any test options so let me
know if there's anything else i need to do

**Comment by mphilbrick211** [comment]
If you rebase the PR and re-run the checks above, the CLA check should turn green. Let me know if it's still not working for you.

**Review by kdmccormick — CHANGES_REQUESTED** [review]
Thanks for catching this @datamatrixnull . The docs are indeed wrong here.

`tutor dev quickstart` was renamed to `tutor dev launch` (running `tutor dev start` isn't needed). Could you update your PR to simply change `quickstart` to `launch`?

**Comment by mphilbrick211** [comment]
Hi @datamatrixnull! Just following up on this :)

**Comment by mphilbrick211** [comment]
> Hi @datamatrixnull! Just following up on this :)

Hi @datamatrixnull - following up to see if you plan to pursue this pull request - please let us know. Thanks!

**Comment by mphilbrick211** [comment]
> > Hi @datamatrixnull! Just following up on this :)
> 
> Hi @datamatrixnull - following up to see if you plan to pursue this pull request - please let us know. Thanks!

Hi @datamatrixnull! I'm going to close this pull request for now, and we can reopen if you choose to pursue in the future. Thanks!

**Comment by openedx-webhooks** [comment]
@datamatrixnull Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/docs.openedx.org&entry.867055334=https://github.com/openedx/docs.openedx.org/pull/316&entry.1484655318=https://github.com/datamatrixnull&entry.752974735=2023-04-21+13:24&entry.1917517419=2023-10-03+01:50&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
